spring.application.name=gw
logging.level.org.springframework.cloud.gateway=DEBUG

server.port=80
spring.cloud.gateway.routes[0].id=msa1
spring.cloud.gateway.routes[0].uri=http://localhost:8881
spring.cloud.gateway.routes[0].predicates[0]=Path=/msa1/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/msa1/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=msa2
spring.cloud.gateway.routes[1].uri=http://localhost:8882
spring.cloud.gateway.routes[1].predicates[0]=Path=/msa2/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/msa2/(?<segment>.*), /${segment}