spring.application.name=configserver

server.port=9000

# github ssh 접속
spring.cloud.config.server.git.uri=git@github.com:hhlee7/msa-config.git
spring.cloud.config.server.git.ignoreLocalSshSettings=true
spring.cloud.config.server.git.private-key=\
-----BEGIN RSA PRIVATE KEY-----\n\
MIIJKQIBAAKCAgEA3IApdgt2wLbZkxF0rIVyJ7SKt7RgrF4B06vDGPF6EXHDAam/\n\
+NpfuNx9bEpqXmjXzfEl5w8Q7yhPZp2HXwc/C7Fr+QezshcmiuwNwGXxFO7V1gnq\n\
a4vYjz4srSrFaWzt4VCqdHmn1gqTBIWHXz7DgbJtTmddgQBNgrBqIG6iYjKkb18z\n\
Y3/95dYFiTJmsfexc1vUjobID+0R5iGtWoLDepZmJHgWbRrfsOOFjsexjkBgonGd\n\
CTYXvZHCt2/gsFKka6JcJnkMDVpfUoPSl1v+ESNQFWzFd/RimYO5ATKf6/fbtPp5\n\
a/gM9QZmlxR0O0GNsuS8YFtTlpcv3aFdulcoLyIe3eovDMgifl6WXKfpC5EOQNFl\n\
RkMDKJJ82rLQvaZr1r1nZ5sJaH0SPgrQIKHNI4ntHwQhs8US/dkyY35TVcehWkqt\n\
gohjdW718iitOZunB3lziH2aT2Rf8W5j5HjxL+sytrwB1OttV4mslWOXgDMhENIb\n\
UiaotydxBBG+4SrWwFKtftQfgKKKva3y6w30UYKPshLgL30cVhIQk0A0fOsp3laf\n\
qlKzypA2/RA8fMGMZPKC/xf9+DhQwcSJJPkY/E2wQfVuEn3vfWF9Iq9bctgXmJ6E\n\
iug7ZI6yNWbD/VjUUbk9rv42YmQdlvQUQ4WrAX5qjMNCb9zfWV7447h2cfkCAwEA\n\
AQKCAgEAwmwXIsi06vPPIIgRslTv9OaSMazQWOuC/NrEaefx1BPU+FBuvsP+BwgT\n\
ZzquU5RqRGJPI077hYSrjjV0OWwwQOUt6STLY0paZ7//2BeK3QRCdDnGAxIJ3zPZ\n\
PM8rxeuQTE1OHult/aLRQvliBa9Xv7JOAwXNQoO71HItAW/Lqn4w0yrEKwWeH9v4\n\
gaJ5Po7CXo8n+owJN1G3qI0lR1tpdVvLsHhafdVmS5gyGVUmz+Ef09wNtSOHB1XQ\n\
tOHm4lHcPDOqwRmWcOewiRdGxsMMYJwcbue7ritEDUxCAjZbIDsp9IeuLG9JLXt5\n\
VdlpKx6ADK73Epc0OuIQCIHSHQ3glRsJ7FTb94u5UddtPmf7I8fF456hbzH1BDpW\n\
QUipKBNzJX+SdHMkemRvvxJ7hCMuftesPVjHANxMYa7EZXbtB6Zl5wER3p3B47jg\n\
8QGsb/xLdkXpzv5ssxoHxv4i4KeAH00pwmM5ifMqCjSW4HNgrTLwR1Uc+iyHVfjM\n\
RjdG9igUnO8jyL8lU5M3rtsKGHJewzfGkJnAT5ezzkjyCyZ+XCFUIfLU+hLADhng\n\
NS3HKYNV1CedEHYC9IHWmGeFZAgd4C4CcKp3ECypiOzbNC00ecW2zvvo0tyS4JKb\n\
TFrc69E7j6CrvNRgd7MOppj2tEs1mNCjwX7UkOIyBD1Q7WeqwqECggEBAPr3FJp+\n\
qlpMu8eANXSRQtnRX9CKKlaR+NXZCAM3CPM9KhqPuBl6S7HC06DB1SRncccJ9tDn\n\
moxiQWzT8HIEsaRUszZSTLdoVq0im50dNmhZuPehUTZoKkdbeqrEKil6v02fHUp0\n\
aXeJOFJYvP6J4iEcQkNlVqgXmkCPbZciA05LWD+CnHcrleZbyUN5bUAGE1EG+jVD\n\
LXtlxt2L3+Ak7p01PO4pKyh1eoylbUkHJJ/G2pXb5fx6d+DN0rtfGZsjWbudAl6j\n\
2poYET3bg5JKgPaPlDMKyyzwu60tQatVwVvzRKfyOGd06MOf1D7znNo8xv1Ffhjp\n\
aib9SD4DlsK0AEUCggEBAODsnsdK5aawBGsyX7S7RvP1cPHyv8L+KVn6hcHHndZ1\n\
YlAa/zuPCOhcybttD8lD1tK0/Y9Yf+7RFcGj0MQn3/lQA2rCAjBr7ncYUx9T7rZS\n\
RBKNrXtm6Pdv5ix1lbT4rrPhzVxFNk4+a3lHVHkSio2KzvoB6MZa4H3uHJuabHjP\n\
Uy71gqsArnBBDlQ7Jx0Ho2kx/f5NvyflDKC+xUC96h24FSMAyLBVk2xZT9nv/33S\n\
8IFz8oZqXwzeGtuz+7IEcrd9SQMpQnqwYsfvjU11SH1GUvaHldWCps0SBWqjDmjs\n\
kMrSrFyFMH8NDzM0GkdoSsMUld7jkBiFQy7zyEZTSCUCggEBAISiSJVOFCIdI7DQ\n\
JXAxxS7w5L6GBtIx21zJkt6AG47R6IqZIib050RPPyFaz5apxQv4TCUkAh3nX8Rw\n\
Tkc0C95ZlU1EOZ9E2WovPCbQ5YxIvuTAsPccHhwQUMgnXFEHukr/qK9MzuCJ+OYs\n\
V9X+cTAmiy6rRB0aPD+ajcSuCSk70KvgD2k788EHCVtLtV182ICeO2Yi1sq8g1lb\n\
Lzp6ylDzbfxAbbq4O8hRNWy/BbAbnDJPQUEqSGja3mCAZjwDds0csb/qwQFnbtVO\n\
Sj7qeTXVs/E15yMdJ1Li9C3k6If8DXDlJsImm02oDrgmb+M288OvEnGACsYIXkHI\n\
C8li8DECggEARradhJJreOhFu13u8Ocf+3ris25aE3fMkFlOzAlx+gaVjhGuxI7H\n\
giYJ1j8Hg4MserokLXjpX6+kY2iZLdJLfBpHuLyd65NDOXYQS/0bQ37BoAOi0vUb\n\
sQ8hEkE1e9vjMPKAmc24sQi2yT4/tIC7xpwpTjhjclkH0w+VNuZpy+GCiXTuS8y/\n\
CtOpKZofReUs3tm0vMq8mlJMkgzn/t62R/mjy4lnjuiYnKvHiwEFFg3HRyuox9GR\n\
aH47e28uZl03o7Bjz/acy+3AYJNTnVKOI7SESLV/ycx1nGtaAJia4yncq6doQP4u\n\
rQLyEGsFCAYl2wcRxy1MFClxYcWK5XExcQKCAQBNT9xCNUnwEjM4CPgsh+sbhCT0\n\
jBkwSoLU0Gy+30Xj1na6t7Lr6D8M7IfLd5pYfiMr82uo2AzdtZiVJNu7ZU6JQLSx\n\
sdQ9OUK9PVHKM9Q+cQrQmlHAmcMSvRxsXdehjiFO4RCI5i7xxYv53Whx8FPGZQqy\n\
TqqQuCkHTCkxGbLsmfpiPhlRMY0RywAUQW+EjRqRW3xyn0z3BBmPqG86uA6xp9jE\n\
J3Euhtgig1jHdSzm6oeVDIusQA32EW6GOghCoFYwIrjxZcnNRSOG1Y1y+0mvS7zF\n\
IVFwvDVcN0mKiaJUksYSv525LE5TcObGGG82Fpon4PshOYH7UpZAkklHQDi2\n\
-----END RSA PRIVATE KEY-----